import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class HyperKnight {
    int inside(int x, int y, int w, int h) {
        if (x < 0) return 0;
        if (y < 0) return 0;
        if (x >= w) return 0;
        if (y >= h) return 0;
        return 1;
    }

    /**
     * Split the board into 5 * 5 areas, test for each area
     *
     * Segmentation
     *
     * @param a
     * @param b
     * @param w
     * @param h
     * @param k
     * @return
     */
    public long countCells(int a, int b, int w, int h, int k) {
        int px[] = new int[]{0, a, b, w - a, w - b, w};
        int py[] = new int[]{0, a, b, h - a, h - b, h};
        Arrays.sort(px);
        Arrays.sort(py);
        long res = 0;
        for (int i = 0; i < 5; i++)
            for (int j = 0; j < 5; j++) {
                int x1 = px[i];
                int x2 = px[i + 1];
                int y1 = py[j];
                int y2 = py[j + 1];
                int dx = x2 - x1;
                int dy = y2 - y1;
                long sq = dx;
                sq *= dy;
                int ans = 0;
                if (sq != 0) {
                    ans += inside(x1 + a, y1 + b, w, h);
                    ans += inside(x1 + a, y1 - b, w, h);
                    ans += inside(x1 - a, y1 + b, w, h);
                    ans += inside(x1 - a, y1 - b, w, h);
                    ans += inside(x1 + b, y1 + a, w, h);
                    ans += inside(x1 - b, y1 + a, w, h);
                    ans += inside(x1 - b, y1 - a, w, h);
                    ans += inside(x1 + b, y1 - a, w, h);
                }
                if (ans == k)
                    res += sq;
            }
        return res;
    }


    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
    private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, int p2, int p3, int p4, boolean hasAnswer, long p5) {
        System.out.print("Test " + testNum + ": [" + p0 + "," + p1 + "," + p2 + "," + p3 + "," + p4);
        System.out.println("]");
        HyperKnight obj;
        long answer;
        obj = new HyperKnight();
        long startTime = System.currentTimeMillis();
        answer = obj.countCells(p0, p1, p2, p3, p4);
        long endTime = System.currentTimeMillis();
        boolean res;
        res = true;
        System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
        if (hasAnswer) {
            System.out.println("Desired answer:");
            System.out.println("\t" + p5);
        }
        System.out.println("Your answer:");
        System.out.println("\t" + answer);
        if (hasAnswer) {
            res = answer == p5;
        }
        if (!res) {
            System.out.println("DOESN'T MATCH!!!!");
        } else if ((endTime - startTime) / 1000.0 >= 2) {
            System.out.println("FAIL the timeout");
            res = false;
        } else if (hasAnswer) {
            System.out.println("Match :-)");
        } else {
            System.out.println("OK, but is it right?");
        }
        System.out.println("");
        return res;
    }

    public static void main(String[] args) {
        boolean all_right;
        all_right = true;

        int p0;
        int p1;
        int p2;
        int p3;
        int p4;
        long p5;

        // ----- test 0 -----
        p0 = 2;
        p1 = 1;
        p2 = 8;
        p3 = 8;
        p4 = 4;
        p5 = 20L;
        all_right = KawigiEdit_RunTest(0, p0, p1, p2, p3, p4, true, p5) && all_right;
        // ------------------

        // ----- test 1 -----
        p0 = 3;
        p1 = 2;
        p2 = 8;
        p3 = 8;
        p4 = 2;
        p5 = 16L;
        all_right = KawigiEdit_RunTest(1, p0, p1, p2, p3, p4, true, p5) && all_right;
        // ------------------

        // ----- test 2 -----
        p0 = 1;
        p1 = 3;
        p2 = 7;
        p3 = 11;
        p4 = 0;
        p5 = 0L;
        all_right = KawigiEdit_RunTest(2, p0, p1, p2, p3, p4, true, p5) && all_right;
        // ------------------

        // ----- test 3 -----
        p0 = 3;
        p1 = 2;
        p2 = 10;
        p3 = 20;
        p4 = 8;
        p5 = 56L;
        all_right = KawigiEdit_RunTest(3, p0, p1, p2, p3, p4, true, p5) && all_right;
        // ------------------

        // ----- test 4 -----
        p0 = 1;
        p1 = 4;
        p2 = 100;
        p3 = 10;
        p4 = 6;
        p5 = 564L;
        all_right = KawigiEdit_RunTest(4, p0, p1, p2, p3, p4, true, p5) && all_right;
        // ------------------

        // ----- test 5 -----
        p0 = 2;
        p1 = 3;
        p2 = 1000000000;
        p3 = 1000000000;
        p4 = 8;
        p5 = 999999988000000036L;
        all_right = KawigiEdit_RunTest(5, p0, p1, p2, p3, p4, true, p5) && all_right;
        // ------------------

        if (all_right) {
            System.out.println("You're a stud (at least on the example cases)!");
        } else {
            System.out.println("Some of the test cases had errors.");
        }
    }
    // PROBLEM STATEMENT
    // Fernando loves to play chess. One day he decided to play chess on an unusually large rectangular board. To compensate for the board's size he also decided to change the distance a knight can move in a single jump.
    //
    // To describe the moves easily, we will now introduce a coordinate system. Each cell of the chessboard can be described using two integers (r,c): its row number and its column number. Now, if we have a piece at (r,c), the move (x,y) takes the piece to the cell (r+x,c+y).
    //
    // The new chess piece will be called an (a,b)-hyperknight. The hyperknight always has 8 possible moves: (+a,+b), (+a,-b), (-a,+b), (-a,-b), (+b,+a), (+b,-a), (-b,+a), and (-b,-a). Note that the original chess knight is a (2,1)-hyperknight.
    //
    // Of course, as the chessboard is finite, it is not always possible to make each of the 8 moves. Some of them may cause our hyperknight to leave the chessboard. A move is called valid if the destination cell is on the chessboard. Fernando would like to know the number of cells on his board such that his hyperknight will have exactly k valid moves from that cell.
    //
    // You are given the ints a, b, numRows, numColumns and k. The values numRows and numColumns define the number of rows and number of columns on the chessboard, respectively. The other three values were already explained above. Compute and return the number of cells on the chessboard that have exactly k valid (a,b)-hyperknight moves.
    //
    // DEFINITION
    // Class:HyperKnight
    // Method:countCells
    // Parameters:int, int, int, int, int
    // Returns:long
    // Method signature:long countCells(int a, int b, int numRows, int numColumns, int k)
    //
    //
    // NOTES
    // -If you wish, you may assume that the rows are numbered 0 through numRows-1 and columns 0 through numColumns-1. However, note that the actual row/column numbers do not matter, as long as they are consecutive.
    //
    //
    // CONSTRAINTS
    // -a will be between 1 and 1,000,000,000 (10^9), inclusive.
    // -b will be between 1 and 1,000,000,000 (10^9), inclusive.
    // -a will not be equal to b.
    // -numRows will be between 1 and 1,000,000,000 (10^9), inclusive.
    // -numColumns will be between 1 and 1,000,000,000 (10^9), inclusive.
    // -2*max(a,b) will be strictly less than min(numRows,numColumns).
    // -k will be between 0 and 8, inclusive.
    //
    //
    // EXAMPLES
    //
    // 0)
    // 2
    // 1
    // 8
    // 8
    // 4
    //
    // Returns: 20
    //
    // This is a standard chessboard. We have a traditional chess knight and we are looking for cells such that the knight has exactly 4 valid moves.
    //
    // 1)
    // 3
    // 2
    // 8
    // 8
    // 2
    //
    // Returns: 16
    //
    //
    //
    // 2)
    // 1
    // 3
    // 7
    // 11
    // 0
    //
    // Returns: 0
    //
    //
    //
    // 3)
    // 3
    // 2
    // 10
    // 20
    // 8
    //
    // Returns: 56
    //
    //
    //
    // 4)
    // 1
    // 4
    // 100
    // 10
    // 6
    //
    // Returns: 564
    //
    //
    //
    // 5)
    // 2
    // 3
    // 1000000000
    // 1000000000
    // 8
    //
    // Returns: 999999988000000036
    //
    //
    //
    // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
