import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class SilverbachConjecture {
    public int[] solve(int n) {
        int len = 2048;
        boolean[] isPrime = new boolean[len];
        Arrays.fill(isPrime, true);
        for (int i = 2; i < len; i++) {
            if (isPrime[i]) {
                for (int j = i + i; j < n; j += i) {
                    isPrime[j] = false;
                }
            }
        }
        Set<Integer> comp = new HashSet<Integer>();
        for (int i = 2; i < n; i++) {
            if (!isPrime[i]) comp.add(i);
        }
        int[] ret = new int[2];
        for (int i : comp) {
            if (comp.contains(n - i)) {
                ret[0] = i;
                ret[1] = n - i;
            }
        }
        return ret;

    }

    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
    private static boolean KawigiEdit_RunTest(int testNum, int p0, boolean hasAnswer, int[] p1) {
        System.out.print("Test " + testNum + ": [" + p0);
        System.out.println("]");
        SilverbachConjecture obj;
        int[] answer;
        obj = new SilverbachConjecture();
        long startTime = System.currentTimeMillis();
        answer = obj.solve(p0);
        long endTime = System.currentTimeMillis();
        boolean res;
        res = true;
        System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
        if (hasAnswer) {
            System.out.println("Desired answer:");
            System.out.print("\t" + "{");
            for (int i = 0; p1.length > i; ++i) {
                if (i > 0) {
                    System.out.print(",");
                }
                System.out.print(p1[i]);
            }
            System.out.println("}");
        }
        System.out.println("Your answer:");
        System.out.print("\t" + "{");
        for (int i = 0; answer.length > i; ++i) {
            if (i > 0) {
                System.out.print(",");
            }
            System.out.print(answer[i]);
        }
        System.out.println("}");
        if (hasAnswer) {
            if (answer.length != p1.length) {
                res = false;
            } else {
                for (int i = 0; answer.length > i; ++i) {
                    if (answer[i] != p1[i]) {
                        res = false;
                    }
                }
            }
        }
        if (!res) {
            System.out.println("DOESN'T MATCH!!!!");
        } else if ((endTime - startTime) / 1000.0 >= 2) {
            System.out.println("FAIL the timeout");
            res = false;
        } else if (hasAnswer) {
            System.out.println("Match :-)");
        } else {
            System.out.println("OK, but is it right?");
        }
        System.out.println("");
        return res;
    }
    public static void main(String[] args) {
        boolean all_right;
        all_right = true;

        int p0;
        int[] p1;

        // ----- test 0 -----
        p0 = 20;
        p1 = new int[] {8, 12};
        all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
        // ------------------

        // ----- test 1 -----
        p0 = 30;
        p1 = new int[] {15, 15};
        all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
        // ------------------

        // ----- test 2 -----
        p0 = 999;
        p1 = new int[] {699, 300};
        all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
        // ------------------

        // ----- test 3 -----
        p0 = 45;
        p1 = new int[] {15, 30};
        all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
        // ------------------

        if (all_right) {
            System.out.println("You're a stud (at least on the example cases)!");
        } else {
            System.out.println("Some of the test cases had errors.");
        }
    }
    // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
