import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class TheKingsArmyDiv2
{
	public int getNumber(String[] state)
	{
		ArrayList<Integer> rList = new ArrayList<Integer>();
        ArrayList<Integer> cList = new ArrayList<Integer>();
        int c = state[0].length(), r = state.length;
        for (int i = 0; i < r; i++) {
            for (int j = 0; j < c; j++) {
                if (state[i].charAt(j) == 'H') {
                    rList.add(i);
                    cList.add(j);
                }
            }
        }
        int n = rList.size();
        if (n == 0) {
            return 2;
        } else {
            for (int i = 0; i < n; i++) {
                for (int j = i + 1; j < n; j++) {
                    if (rList.get(i) == rList.get(j) && cList.get(i) + 1 == cList.get(j)) {
                        return 0;
                    }
                    if (cList.get(i) == cList.get(j) && rList.get(i) + 1 == rList.get(j)) {
                        return 0;
                    }
                }
            }
            return 1;
        }
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, int p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		TheKingsArmyDiv2 obj;
		int answer;
		obj = new TheKingsArmyDiv2();
		long startTime = System.currentTimeMillis();
		answer = obj.getNumber(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p1);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p1;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		int p1;
		
		// ----- test 0 -----
		p0 = new String[]{"SSSSS","SSHHS","SSSSS"};
		p1 = 0;
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"SSSSS","SSHSH","HSSSS"};
		p1 = 1;
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"SSS","SSS","SSS"};
		p1 = 2;
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"HSHSHSH","SSSHSSS","SSHSHSS","SHSHSHS"};
		p1 = 1;
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{"HHSH","HHHS","HSSS","SHSH","HHHS","HSHH","SSSH"};
		p1 = 0;
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// 
	// The King of Byteland has an army that consists of R*C soldiers.
	// He has just arranged the soldiers into a grid with R rows and C columns.
	// Two soldiers are neighbors if they stand next to each other in a row or in a column.
	// 
	// 
	// 
	// 
	// Each of the soldiers is currently either happy or sad.
	// You are given their current states in a String[] state with R elements, each containing C characters.
	// The character state[i][j] is either 'H' (if the soldier in row i, column j is happy) or 'S' (if that soldier is sad).
	// 
	// 
	// 
	// 
	// Happiness is contagious.
	// Whenever two neighbors are both happy, they will tell each other jokes and after a minute that will make all of their neighbors happy as well.
	// 
	// 
	// 
	// 
	// Here's an example.
	// There are two happy neighbors among many sad soldiers:
	// 
	// 
	// 
	// 
	// {"SSSSS",
	//  "SSHHS",
	//  "SSSSS"}
	// 
	// 
	// 
	// 
	// This is the situation after one minute: all of their neighbors are happy now.
	// 
	// 
	// 
	// 
	// {"SSHHS",
	//  "SHHHH",
	//  "SSHHS"}
	// 
	// 
	// 
	// 
	// And this is the situation after another minute. Now all the neighbors of the soldiers that are currently happy became happy as well.
	// 
	// 
	// 
	// 
	// {"SHHHH",
	//  "HHHHH",
	//  "SHHHH"}
	// 
	// 
	// 
	// 
	// After another minute, all the soldiers in the King's army would be happy.
	// 
	// 
	// 
	// 
	// The King wants all his soldiers to be happy.
	// Sometimes it's easy, as in the above example: all he has to do is wait for a while and all soldiers will become happy.
	// However, it is not always the case.
	// For example, in the situation below the happiness would not spread anywhere, each soldier would remain in his original state forever.
	// (Note that a single happy soldier does not make his neighbors happy.)
	// 
	// 
	// 
	// 
	// {"SSSSS",
	//  "SSHSH",
	//  "HSSSS"}
	// 
	// 
	// 
	// 
	// The King can make a soldier happy by giving him an award for excellent service.
	// Obviously, the King could make all soldiers happy by giving awards to all of them.
	// But the King is smart and knows that there is a better solution.
	// He will only give the awards to a few carefully selected soldiers and then he will simply wait until the happiness spreads to the rest of the army.
	// 
	// 
	// 
	// 
	// You are given the String[] state.
	// Compute and return the smallest number of awards the king has to give to make all soldiers happy in the end.
	// 
	// 
	// DEFINITION
	// Class:TheKingsArmyDiv2
	// Method:getNumber
	// Parameters:String[]
	// Returns:int
	// Method signature:int getNumber(String[] state)
	// 
	// 
	// CONSTRAINTS
	// -state will contain between 3 and 50 elements, inclusive.
	// -Each element of state will contain between 3 and 50 characters, inclusive.
	// -Each element of state will contain the same number of characters.
	// -Each character in each element of state will be either 'H' or 'S'.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// {"SSSSS",
	//  "SSHHS",
	//  "SSSSS"}
	// 
	// Returns: 0
	// 
	// This is the first example in the problem statement. No awards are necessary, all soldiers will become happy anyway.
	// 
	// 1)
	// {"SSSSS",
	//  "SSHSH",
	//  "HSSSS"}
	// 
	// Returns: 1
	// 
	// This is the second example in the problem statement. The King needs to give at least one award. One optimal solution is to give an award to the soldier in row 1, column 3. (Both indices are 0-based.)
	// 
	// 2)
	// {"SSS",
	//  "SSS",
	//  "SSS"}
	// 
	// Returns: 2
	// 
	// Here the King must give awards to two soldiers.
	// 
	// 3)
	// {"HSHSHSH", "SSSHSSS", "SSHSHSS", "SHSHSHS"}
	// 
	// Returns: 1
	// 
	// 
	// 
	// 4)
	// {"HHSH", "HHHS", "HSSS", "SHSH", "HHHS", "HSHH", "SSSH"}
	// 
	// Returns: 0
	// 
	// 
	// 
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
