import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class RobotHerbDiv2 {
    public int getdist(int T, int[] a) {
        int x = 0, y = 0, d = 0;
        int[][] direction = {{0, 1}, {-1, 0}, {0, -1}, {1, 0}};
        for (int i = 0; i < T; i++) {
            for (int ai : a) {
                x += direction[d][0] * ai;
                y += direction[d][1] * ai;
                d += (ai % 4);
                d %= 4;
            }
        }
        return Math.abs(x) + Math.abs(y);
    }

    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
    private static boolean KawigiEdit_RunTest(int testNum, int p0, int[] p1, boolean hasAnswer, int p2) {
        System.out.print("Test " + testNum + ": [" + p0 + "," + "{");
        for (int i = 0; p1.length > i; ++i) {
            if (i > 0) {
                System.out.print(",");
            }
            System.out.print(p1[i]);
        }
        System.out.print("}");
        System.out.println("]");
        RobotHerbDiv2 obj;
        int answer;
        obj = new RobotHerbDiv2();
        long startTime = System.currentTimeMillis();
        answer = obj.getdist(p0, p1);
        long endTime = System.currentTimeMillis();
        boolean res;
        res = true;
        System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
        if (hasAnswer) {
            System.out.println("Desired answer:");
            System.out.println("\t" + p2);
        }
        System.out.println("Your answer:");
        System.out.println("\t" + answer);
        if (hasAnswer) {
            res = answer == p2;
        }
        if (!res) {
            System.out.println("DOESN'T MATCH!!!!");
        } else if ((endTime - startTime) / 1000.0 >= 2) {
            System.out.println("FAIL the timeout");
            res = false;
        } else if (hasAnswer) {
            System.out.println("Match :-)");
        } else {
            System.out.println("OK, but is it right?");
        }
        System.out.println("");
        return res;
    }
    public static void main(String[] args) {
        boolean all_right;
        all_right = true;

        int p0;
        int[] p1;
        int p2;

        // ----- test 0 -----
        p0 = 1;
        p1 = new int[] {1,2,3};
        p2 = 2;
        all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
        // ------------------

        // ----- test 1 -----
        p0 = 100;
        p1 = new int[] {1};
        p2 = 0;
        all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
        // ------------------

        // ----- test 2 -----
        p0 = 5;
        p1 = new int[] {1,1,2};
        p2 = 10;
        all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
        // ------------------

        // ----- test 3 -----
        p0 = 100;
        p1 = new int[] {400000};
        p2 = 40000000;
        all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
        // ------------------

        if (all_right) {
            System.out.println("You're a stud (at least on the example cases)!");
        } else {
            System.out.println("Some of the test cases had errors.");
        }
    }
    // PROBLEM STATEMENT
    // Robot Herb is playing on an infinite square grid.
    // At any moment, Herb stands on one of the squares and he faces one of the four cardinal directions.
    // In his memory, Herb has a program.
    // The program is a sequence of commands.
    // For each i, the i-th of these commands has the following form:
    //
    // First move forward a[i] tiles.
    // Then turn 90 degrees to the right, a[i] times in a row.
    //
    // Herb has decided to run the program T times.
    // You are given the int T and the int[] a that describes Herb's program.
    // Let A be the initial position of Herb and B be his position after the program was executed T times. Return the Manhattan distance between tiles A and B.
    //
    // DEFINITION
    // Class:RobotHerbDiv2
    // Method:getdist
    // Parameters:int, int[]
    // Returns:int
    // Method signature:int getdist(int T, int[] a)
    //
    //
    // NOTES
    // -Let's introduce a Cartesian coordinate system on the grid so that each cardinal direction is parallel to one of the axes. The Manhattan distance between two tiles with centers at points (x1, y1) and (x2, y2) is defined as |x1-x2| + |y1-y2|.
    //
    //
    // CONSTRAINTS
    // -T will be between 1 and 100, inclusive.
    // -a will contain between 1 and 50 elements, inclusive.
    // -Each element of a will be between 1 and 400,000, inclusive.
    //
    //
    // EXAMPLES
    //
    // 0)
    // 1
    // {1,2,3}
    //
    // Returns: 2
    //
    // Suppose that initially Herb stands on the tile with center at (0, 0) and faces the positive y direction. The program will get executed as follows:
    //
    //                        tile         direction
    // After 1st command:     (0, 1)       positive x
    // After 2nd command:     (2, 1)       negative x
    // After 3rd command:     (-1, 1)      negative y
    //
    // The manhattan distance between the initial and the final positions is |-1| + |1| = 2.
    //
    // 1)
    // 100
    // {1}
    //
    // Returns: 0
    //
    //
    //
    // 2)
    // 5
    // {1,1,2}
    //
    // Returns: 10
    //
    //
    //
    // 3)
    // 100
    // {400000}
    //
    // Returns: 40000000
    //
    //
    //
    // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
