import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class FauxPalindromes
{
	public String classifyIt(String word)
	{
        if (isPalin(word)) return "PALINDROME";
        StringBuilder sb = new StringBuilder(word);
        for (int i = 0; i < sb.length(); i++) {
            while (i + 1 < sb.length() && sb.charAt(i) == sb.charAt(i + 1)) {
                sb.deleteCharAt(i);
            }
        }
        if (isPalin(sb.toString())) {
            return "FAUX";
        } else {
            return "NOT EVEN FAUX";
        }
	}

    public boolean isPalin(String word) {
        int left = 0, right = word.length() - 1;
        boolean isPalin = true;
        while (left < right) {
            if (word.charAt(left) != word.charAt(right)) {
                isPalin = false;
                break;
            } else {
                left++;
                right--;
            }
        }
        return isPalin;
    }
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String p0, boolean hasAnswer, String p1) {
		System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"");
		System.out.println("]");
		FauxPalindromes obj;
		String answer;
		obj = new FauxPalindromes();
		long startTime = System.currentTimeMillis();
		answer = obj.classifyIt(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p1 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p1);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String p0;
		String p1;
		
		// ----- test 0 -----
		p0 = "ANA";
		p1 = "PALINDROME";
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = "AAAAANNAA";
		p1 = "FAUX";
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = "LEGENDARY";
		p1 = "NOT EVEN FAUX";
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = "XXXYTYYTTYX";
		p1 = "FAUX";
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = "TOPCOODEREDOOCPOT";
		p1 = "PALINDROME";
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = "TOPCODEREDOOCPOT";
		p1 = "FAUX";
		all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 6 -----
		p0 = "XXXXYYYYYZZXXYYY";
		p1 = "NOT EVEN FAUX";
		all_right = KawigiEdit_RunTest(6, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// A word is a palindrome if it can be read the same forwards and backwards. For example, the strings "ANA", "AAXAA", "Z" and "XYYYYYX" are palindromes (quotes for clarity).
	// 
	// A word is a faux palindrome if, after replacing every group of consecutive equal letters with a single instance of the letter, the resulting word is a palindrome. For example, the string "AAAAANNAA" is a faux palindrome. A detailed explanation why this is a faux palindrome is given below in Example 1.
	// Other examples of faux palindromes are the strings "AAAAAAAAAAAAAAAXA and "XYX". Note that every palindrome is also a faux palindrome.
	// 
	// You are given a String word. You are asked to classify it.
	// If word is a palindrome, return "PALINDROME" (quotes for clarity, returned values are case sensitive).
	// If word is not a palindrome but is a faux palindrome, return "FAUX".
	// In case word is not a faux palindrome, return "NOT EVEN FAUX".
	// 
	// 
	// 
	// DEFINITION
	// Class:FauxPalindromes
	// Method:classifyIt
	// Parameters:String
	// Returns:String
	// Method signature:String classifyIt(String word)
	// 
	// 
	// CONSTRAINTS
	// -word will contain between 1 and 50 characters, inclusive.
	// -The characters in word will be upper case letters between 'A' and 'Z', inclusive (quotes for clarity).
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// "ANA"
	// 
	// Returns: "PALINDROME"
	// 
	// "ANA" reads the same from left to right and right to left.
	// 
	// 1)
	// "AAAAANNAA"
	// 
	// Returns: "FAUX"
	// 
	// This is obviously not a palindrome. Now suppose that we replace each group of consecutive equal letters by a single copy of that letter. That is, we change "AAAAA" to "A", "NN" to "N", and "AA" to "A". In this way we will obtain the new string "ANA", which is a palindrome. Hence the original string is a faux palindrome.
	// 
	// 2)
	// "LEGENDARY"
	// 
	// Returns: "NOT EVEN FAUX"
	// 
	// The word "LEGENDARY" already does not contain any group of consecutive equal letters and it is not a palindrome.
	// 
	// 3)
	// "XXXYTYYTTYX"
	// 
	// Returns: "FAUX"
	// 
	// After replacing the groups of consecutive equal letters with a single letter, the string becomes "XYTYTYX". "XYTYTYX" is a palindrome.
	// 
	// 4)
	// "TOPCOODEREDOOCPOT"
	// 
	// Returns: "PALINDROME"
	// 
	// This word contains some groups of consecutive equal letters, but it is already a palindrome without replacing them by single letters.
	// 
	// 5)
	// "TOPCODEREDOOCPOT"
	// 
	// Returns: "FAUX"
	// 
	// 
	// 
	// 6)
	// "XXXXYYYYYZZXXYYY"
	// 
	// Returns: "NOT EVEN FAUX"
	// 
	// 
	// 
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
