import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class IdentifyingWood
{
	public String check(String s, String t)
	{
        int i = 0, j = 0;
        while (i < s.length() && j < t.length()) {
            if (s.charAt(i) == t.charAt(j)) {
                i++;
                j++;
            } else {
                i++;
            }
        }
		return (j == t.length()) ? "Yep, it's wood." : "Nope.";
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String p0, String p1, boolean hasAnswer, String p2) {
		System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"" + "," + "\"" + p1 + "\"");
		System.out.println("]");
		IdentifyingWood obj;
		String answer;
		obj = new IdentifyingWood();
		long startTime = System.currentTimeMillis();
		answer = obj.check(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p2 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p2);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String p0;
		String p1;
		String p2;
		
		// ----- test 0 -----
		p0 = "absdefgh";
		p1 = "asdf";
		p2 = "Yep, it's wood.";
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = "oxoxoxox";
		p1 = "ooxxoo";
		p2 = "Nope.";
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = "oxoxoxox";
		p1 = "xxx";
		p2 = "Yep, it's wood.";
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = "qwerty";
		p1 = "qwerty";
		p2 = "Yep, it's wood.";
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = "string";
		p1 = "longstring";
		p2 = "Nope.";
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// 
	// We call a pair of Strings (s, t) "wood" if t is contained in s as a subsequence. (See Notes for a formal definition.)
	// 
	// 
	// 
	// Given Strings s and t, return the String "Yep, it's wood." (quotes for clarity) if the pair (s, t) is wood and "Nope." otherwise.
	// 
	// 
	// DEFINITION
	// Class:IdentifyingWood
	// Method:check
	// Parameters:String, String
	// Returns:String
	// Method signature:String check(String s, String t)
	// 
	// 
	// NOTES
	// -String t is contained in string s as a subsequence if we can obtain t by removing zero or more (not necessarily consecutive) characters from s.
	// 
	// 
	// CONSTRAINTS
	// -s and t will consist only of lowercase English letters.
	// -s and t will each be between 1 and 10 characters long, inclusive.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// "absdefgh"
	// "asdf"
	// 
	// Returns: "Yep, it's wood."
	// 
	// 
	// 
	// 1)
	// "oxoxoxox"
	// "ooxxoo"
	// 
	// Returns: "Nope."
	// 
	// 
	// 
	// 2)
	// "oxoxoxox"
	// "xxx"
	// 
	// Returns: "Yep, it's wood."
	// 
	// 
	// 
	// 3)
	// "qwerty"
	// "qwerty"
	// 
	// Returns: "Yep, it's wood."
	// 
	// 
	// 
	// 4)
	// "string"
	// "longstring"
	// 
	// Returns: "Nope."
	// 
	// 
	// 
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
