import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class EllysTSP
{
	public int getMax(String places)
	{
        int c = 0, v = 0;
		for (char ch : places.toCharArray()) {
           if (ch == 'C') c++;
           else v++;
        }
        if (c == v) {
            return c + v;
        } else {
            return 2 * Math.min(c, v) + 1;
        }
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String p0, boolean hasAnswer, int p1) {
		System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"");
		System.out.println("]");
		EllysTSP obj;
		int answer;
		obj = new EllysTSP();
		long startTime = System.currentTimeMillis();
		answer = obj.getMax(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p1);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p1;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String p0;
		int p1;
		
		// ----- test 0 -----
		p0 = "CVVVC";
		p1 = 5;
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = "VVV";
		p1 = 1;
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = "VVVVCVV";
		p1 = 3;
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = "CVCVCVC";
		p1 = 7;
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = "V";
		p1 = 1;
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// Everybody who has lived in a village knows how expensive the things from the city are. And everybody who has lived in the city knows how expensive the things from the village are. Elly decided to use these observations to make some profit. She will start at some city or village, buy cheap stuff there, go to a place of the opposite type (village if she started in a city, or city if she started in a village) and sell it at a profit there, buying new stuff for the next place (again of the opposite type) and so on. Shortly after she leaves a city or village, the inhabitants realize how she tricked them and get angry at her, so she cannot go to the same place twice.
	// Elly cannot predict the actual profits she will make while using this strategy. Therefore she decided that she simply wants to visit as many places as possible. Of course, she has to alternate between visiting a village and visiting a city, and she may not visit the same place twice.
	// 
	// You are given a String places that describes all places Elly can visit. The i-th character of places is 'V' if the i-th place is a village, or 'C' if it is a city. Return the maximal number of places she can visit according to the rules above.
	// 
	// DEFINITION
	// Class:EllysTSP
	// Method:getMax
	// Parameters:String
	// Returns:int
	// Method signature:int getMax(String places)
	// 
	// 
	// NOTES
	// -Elly can travel directly between any two places.
	// -The minimal answer is 1 as she can start by visiting any one of the available places.
	// -The answer will never exceed the length of places, since she is not allowed to visit the same place more than once.
	// 
	// 
	// CONSTRAINTS
	// -places will contain between 1 and 50 characters, inclusive.
	// -Each character of places will be either 'V' or 'C'.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// "CVVVC"
	// 
	// Returns: 5
	// 
	// It is possible to visit all 5 places.
	// One solution is to start at place 1 (a village), go to place 0 (a city), then to place 2 (a village), place 4 (a city), and finally to place 3 (a village).
	// 
	// 1)
	// "VVV"
	// 
	// Returns: 1
	// 
	// She may start by visiting any of the three villages. As there are no cities, she cannot make any more travels.
	// 
	// 2)
	// "VVVVCVV"
	// 
	// Returns: 3
	// 
	// There is only one city among the places. Elly can go to any of the villages, then go to the city, and then to one of the other villages. Thus, the optimal result is 3.
	// 
	// 3)
	// "CVCVCVC"
	// 
	// Returns: 7
	// 
	// Just visit the locations in the order in which they are given.
	// 
	// 4)
	// "V"
	// 
	// Returns: 1
	// 
	// With only one place there is not much choice what to do.
	// 
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
