import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class PlatypusDuckAndBeaver
{
	public int minimumAnimals(int webbedFeet, int duckBills, int beaverTails)
	{
        for (int p = 0; p <= Math.min(duckBills, beaverTails); p++) {
            int remainF = webbedFeet - p * 4;
            int remainB = duckBills - p;
            int remainT = beaverTails - p;
            if (remainF == remainB * 2 + remainT * 4) {
                return p + remainT + remainB;
            }
        }
        return -1;
    }
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, int p2, boolean hasAnswer, int p3) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + p1 + "," + p2);
		System.out.println("]");
		PlatypusDuckAndBeaver obj;
		int answer;
		obj = new PlatypusDuckAndBeaver();
		long startTime = System.currentTimeMillis();
		answer = obj.minimumAnimals(p0, p1, p2);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p3);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p3;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int p0;
		int p1;
		int p2;
		int p3;
		
		// ----- test 0 -----
		p0 = 4;
		p1 = 1;
		p2 = 1;
		p3 = 1;
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = 0;
		p1 = 0;
		p2 = 0;
		p3 = 0;
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = 10;
		p1 = 2;
		p2 = 2;
		p3 = 3;
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = 60;
		p1 = 10;
		p2 = 10;
		p3 = 20;
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = 1000;
		p1 = 200;
		p2 = 200;
		p3 = 300;
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// Your friend the farmer liked to use the following method to count the number of beavers and ducks present on the farm: He would first find three ints webbedFeet, duckBills and beaverTails, representing  the number of webbed feet, duck bills and beaver tails he could count and then he used those numbers to find the number of ducks and beavers on the farm. (A duck has one duck bill and two webbed feet. A beaver has one beaver tail and four webbed feet.)
	// 
	// The method worked great until he received news that there could be a platypus invasion on the farm. A platypus is a marvellous creature that has 4 webbed feet, a duck bill and a beaver tail. Our farmer is justifiably confused. Help him find out that his method is still useful. You are given ints webbedFeet, duckBills and beaverTails that specify the number of webbed feet, duck bills and beaver tails  the farmer has counted, respectively. Return the total number of animals (ducks, beavers, and platypuses) on the farm. The constraints guarantee that there will be exactly one solution.
	// 
	// DEFINITION
	// Class:PlatypusDuckAndBeaver
	// Method:minimumAnimals
	// Parameters:int, int, int
	// Returns:int
	// Method signature:int minimumAnimals(int webbedFeet, int duckBills, int beaverTails)
	// 
	// 
	// CONSTRAINTS
	// -webbedFeet, duckBills and beaverTails will each be between 0 and 1000, inclusive.
	// -There will be exactly one way to assign the number of ducks, beavers and platypuses such that the total number of each specific kind of body part matches webbedFeet, duckBills and beaverTails, respectively.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// 4
	// 1
	// 1
	// 
	// Returns: 1
	// 
	// If there is only one platypus, it will have 4 webbed feet, 1 beaver tail and 1 duck bill. Matching the description.
	// 
	// 1)
	// 0
	// 0
	// 0
	// 
	// Returns: 0
	// 
	// 
	// 
	// 2)
	// 10
	// 2
	// 2
	// 
	// Returns: 3
	// 
	// One platypus, one duck and one beaver.
	// 
	// 3)
	// 60
	// 10
	// 10
	// 
	// Returns: 20
	// 
	// 10 ducks and 10 beavers.
	// 
	// 4)
	// 1000
	// 200
	// 200
	// 
	// Returns: 300
	// 
	// 
	// 
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
