import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class RobotOnMoonEasy
{
	public String isSafeCommand(String[] board, String S)
	{
        int n = board.length;
        int m = board[0].length();

	    int r = 0, c = 0;
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < m; j++) {
                if (board[i].charAt(j) == 'S') {
                    r = i;
                    c = j;
                }
            }
        }
        boolean result = true;
        for (char d : S.toCharArray()) {
            switch (d) {
                case 'U':
                    if (r - 1 >= 0) {
                        if(board[r - 1].charAt(c) != '#') r--;
                    } else {
                        result = false;
                    }
                    break;
                case 'D':
                    if (r + 1 < n) {
                        if(board[r + 1].charAt(c) != '#') r++;
                    } else {
                        result = false;
                    }
                    break;
                case 'L':
                    if (c - 1 >= 0) {
                        if (board[r].charAt(c - 1) != '#') c--;
                    } else {
                        result = false;
                    }
                    break;
                case 'R':
                    if (c + 1 < m) {
                        if (board[r].charAt(c + 1) != '#') c++;
                    } else {
                        result = false;
                    }
                    break;
            }
        }
        return result ? "Alive" : "Dead";

	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, String p1, boolean hasAnswer, String p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}" + "," + "\"" + p1 + "\"");
		System.out.println("]");
		RobotOnMoonEasy obj;
		String answer;
		obj = new RobotOnMoonEasy();
		long startTime = System.currentTimeMillis();
		answer = obj.isSafeCommand(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p2 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p2);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		String p1;
		String p2;
		
		// ----- test 0 -----
		p0 = new String[]{".....",".###.","..S#.","...#."};
		p1 = "URURURURUR";
		p2 = "Alive";
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{".....",".###.","..S..","...#."};
		p1 = "URURURURUR";
		p2 = "Dead";
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{".....",".###.","..S..","...#."};
		p1 = "URURU";
		p2 = "Alive";
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"#####","#...#","#.S.#","#...#","#####"};
		p1 = "DRULURLDRULRUDLRULDLRULDRLURLUUUURRRRDDLLDD";
		p2 = "Alive";
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{"#####","#...#","#.S.#","#...#","#.###"};
		p1 = "DRULURLDRULRUDLRULDLRULDRLURLUUUURRRRDDLLDD";
		p2 = "Dead";
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = new String[]{"S"};
		p1 = "R";
		p2 = "Dead";
		all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// There is a robot on the moon.
	// You are given a String[] board containing the map of a rectangular area.
	// The robot is currently located somewhere in that area.
	// In the map, the character '.' (period) represents an empty square, 'S' represents an empty square that currently contains the robot, and '#' represents an obstacle.
	// 
	// 
	// You are also given a String S.
	// This String represents a sequence of commands we are going to send to the robot.
	// Each character in S is one of 'U', 'D', 'L', and 'R', representing a step up, down, left, and right, respectively.
	// 
	// 
	// Whenever the robot receives a command, one of three things will happen:
	// 
	// If the requested move leads to an empty square, the robot performs the move.
	// If the requested move leads to a square with an obstacle, the robot ignores the command and remains in place.
	// If the requested move leads out of the mapped area, the robot leaves the mapped area and dies immediately.
	// 
	// 
	// 
	// Given the map and the sequence of commands, compute whether the robot will survive.
	// Return "Alive" (quotes for clarity) if the robot is still somewhere on the map after the last command.
	// Otherwise, return "Dead".
	// Note that the return value is case-sensitive.
	// 
	// DEFINITION
	// Class:RobotOnMoonEasy
	// Method:isSafeCommand
	// Parameters:String[], String
	// Returns:String
	// Method signature:String isSafeCommand(String[] board, String S)
	// 
	// 
	// NOTES
	// -The direction 'U' corresponds to moving from board[i][j] to board[i-1][j]. The direction 'L' corresponds to moving from board[i][j] to board[i][j-1].
	// 
	// 
	// CONSTRAINTS
	// -board will contain between 1 and 50 elements, inclusive.
	// -Each element of board will contain between 1 and 50 characters.
	// -Each element of board will contain the same number of characters.
	// -The characters in board will be '.', '#' or 'S'.
	// -There will be exactly one 'S' in board.
	// -S will contain between 1 and 50 characters, inclusive.
	// -Each character in S will be one of 'U', 'D', 'L', 'R'.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// {".....",
	//  ".###.",
	//  "..S#.",
	//  "...#."}
	// "URURURURUR"
	// 
	// Returns: "Alive"
	// 
	// The robot will never move from its starting location: commands 'U' and 'R' are sending it into obstacles, so the robot ignores them.
	// 
	// 1)
	// {".....",
	//  ".###.",
	//  "..S..",
	//  "...#."}
	// "URURURURUR"
	// 
	// Returns: "Dead"
	// 
	// This time there is no obstacle on the robot's right side. Its execution of commands will look as follows:
	// 
	// 'U' leads into an obstacle. The robot ignores it.
	// 'R' leads into an empty square. The robot makes a step to the right.
	// 'U' leads into an obstacle. The robot ignores it.
	// 'R' leads into an empty square. The robot makes a step to the right.
	// The next 'U' now leads into an empty square. The robot makes a step up. After this step, the robot is in row 1, column 4. (Both indices are 0-based.)
	// 'R' leads out of the map. The robot steps out of the map and dies. The remaining four commands never get executed - the robot is already dead.
	// 
	// 
	// 2)
	// {".....",
	//  ".###.",
	//  "..S..",
	//  "...#."}
	// "URURU"
	// 
	// Returns: "Alive"
	// 
	// 
	// 
	// 3)
	// {"#####",
	//  "#...#",
	//  "#.S.#",
	//  "#...#",
	//  "#####"}
	// "DRULURLDRULRUDLRULDLRULDRLURLUUUURRRRDDLLDD"
	// 
	// Returns: "Alive"
	// 
	// There are obstacles all around the map. Regardless of how the robot moves, it is safe - the obstacles will prevent it from leaving the map.
	// 
	// 4)
	// {"#####",
	//  "#...#",
	//  "#.S.#",
	//  "#...#",
	//  "#.###"}
	// "DRULURLDRULRUDLRULDLRULDRLURLUUUURRRRDDLLDD"
	// 
	// Returns: "Dead"
	// 
	// After some steps the robot will leave the map from the only empty square in the bottom row of the map.
	// 
	// 5)
	// {"S"}
	// "R"
	// 
	// Returns: "Dead"
	// 
	// 
	// 
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
