import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class MonstersValley2 {
    int n;
    int[] dread, price;
    public int minimumPrice(int[] dread, int[] price) {
        n = dread.length;
        this.dread = dread;
        this.price = price;

        return cost(0, 0L);
    }

    public int cost(int pos, long power) {
        if (pos == n) {
            return 0;
        }
        int cost = 2 * n;
        if (power >= dread[pos]) {
            cost = Math.min(cost, cost(pos + 1, power));
        }
        cost = Math.min(cost, cost(pos + 1, power + dread[pos]) + price[pos]);
        return cost;
    }

    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
    private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int[] p1, boolean hasAnswer, int p2) {
        System.out.print("Test " + testNum + ": [" + "{");
        for (int i = 0; p0.length > i; ++i) {
            if (i > 0) {
                System.out.print(",");
            }
            System.out.print(p0[i]);
        }
        System.out.print("}" + "," + "{");
        for (int i = 0; p1.length > i; ++i) {
            if (i > 0) {
                System.out.print(",");
            }
            System.out.print(p1[i]);
        }
        System.out.print("}");
        System.out.println("]");
        MonstersValley2 obj;
        int answer;
        obj = new MonstersValley2();
        long startTime = System.currentTimeMillis();
        answer = obj.minimumPrice(p0, p1);
        long endTime = System.currentTimeMillis();
        boolean res;
        res = true;
        System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
        if (hasAnswer) {
            System.out.println("Desired answer:");
            System.out.println("\t" + p2);
        }
        System.out.println("Your answer:");
        System.out.println("\t" + answer);
        if (hasAnswer) {
            res = answer == p2;
        }
        if (!res) {
            System.out.println("DOESN'T MATCH!!!!");
        } else if ((endTime - startTime) / 1000.0 >= 2) {
            System.out.println("FAIL the timeout");
            res = false;
        } else if (hasAnswer) {
            System.out.println("Match :-)");
        } else {
            System.out.println("OK, but is it right?");
        }
        System.out.println("");
        return res;
    }
    public static void main(String[] args) {
        boolean all_right;
        all_right = true;

        int[] p0;
        int[] p1;
        int p2;

        // ----- test 0 -----
        p0 = new int[] {8,5,10};
        p1 = new int[] {1,1,2};
        p2 = 2;
        all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
        // ------------------

        // ----- test 1 -----
        p0 = new int[] {1,2,4,1000000000};
        p1 = new int[] {1,1,1,2};
        p2 = 5;
        all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
        // ------------------

        // ----- test 2 -----
        p0 = new int[] {200,107,105,206,307,400};
        p1 = new int[] {1,2,1,1,1,2};
        p2 = 2;
        all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
        // ------------------

        // ----- test 3 -----
        p0 = new int[] {5216,12512,613,1256,66,17202,30000,23512,2125,33333};
        p1 = new int[] {2,2,1,1,1,1,2,1,2,1};
        p2 = 5;
        all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
        // ------------------

        if (all_right) {
            System.out.println("You're a stud (at least on the example cases)!");
        } else {
            System.out.println("Some of the test cases had errors.");
        }
    }
    // PROBLEM STATEMENT
    // Manao is traversing a valley inhabited by monsters. During his journey, he will encounter several monsters one by one. The scariness of each monster is a positive integer. Some monsters may be scarier than others. The i-th (0-based index) monster Manao will meet has scariness equal to dread[i].
    //
    // Manao is not going to fight the monsters. Instead, he will bribe some of them and make them join him. To bribe the i-th monster, Manao needs price[i] gold coins. The monsters are not too greedy, therefore each value in price will be either 1 or 2.
    //
    // At the beginning, Manao travels alone. Each time he meets a monster, he first has the option to bribe it, and then the monster may decide to attack him. A monster will attack Manao if and only if he did not bribe it and its scariness is strictly greater than the total scariness of all monsters in Manao's party. In other words, whenever Manao encounters a monster that would attack him, he has to bribe it. If he encounters a monster that would not attack him, he may either bribe it, or simply walk past the monster.
    //
    //
    //
    // Consider this example: Manao is traversing the valley inhabited by the Dragon, the Hydra and the Killer Rabbit. When he encounters the Dragon, he has no choice but to bribe him, spending 1 gold coin (in each test case, Manao has to bribe the first monster he meets, because when he travels alone, the total scariness of monsters in his party is zero). When they come by the Hydra, Manao can either pass or bribe her. In the end, he needs to get past the Killer Rabbit. If Manao bribed the Hydra, the total scariness of his party exceeds the Rabbit's, so they will pass. Otherwise, the Rabbit has to be bribed for two gold coins. Therefore, the optimal choice is to bribe the Hydra and then to walk past the Killer Rabbit. The total cost of getting through the valley this way is 2 gold coins.
    //
    // You are given the int[]s dread and price. Compute the minimum price Manao will pay to safely pass the valley.
    //
    // DEFINITION
    // Class:MonstersValley2
    // Method:minimumPrice
    // Parameters:int[], int[]
    // Returns:int
    // Method signature:int minimumPrice(int[] dread, int[] price)
    //
    //
    // CONSTRAINTS
    // -dread will contain between 1 and 20 elements, inclusive.
    // -Each element of dread will be between 1 and 2,000,000,000, inclusive.
    // -price will contain between the same number of elements as dread.
    // -Each element of price will be either 1 or 2.
    //
    //
    // EXAMPLES
    //
    // 0)
    // {8, 5, 10}
    // {1, 1, 2}
    //
    // Returns: 2
    //
    // The example from the problem statement.
    //
    // 1)
    // {1, 2, 4, 1000000000}
    // {1, 1, 1, 2}
    //
    // Returns: 5
    //
    // Manao has to bribe all monsters in the valley.
    //
    //
    // 2)
    // {200, 107, 105, 206, 307, 400}
    // {1, 2, 1, 1, 1, 2}
    //
    // Returns: 2
    //
    // Manao can bribe monsters 0 and 3.
    //
    //
    // 3)
    // {5216, 12512, 613, 1256, 66, 17202, 30000, 23512, 2125, 33333}
    // {2, 2, 1, 1, 1, 1, 2, 1, 2, 1}
    //
    // Returns: 5
    //
    // Bribing monsters 0, 1 and 5 is sufficient to pass safely.
    //
    // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
