import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;

/**
 * SRM 605
 */
public class AlienAndSetDiv2 {
    public int getNumber(int N, int K) {
        int maxN = 128, maxK = 10;
        int MOD = 1000000007;
        // use filled slots + last k fills (bitmask) as state description
        int[][] dp = new int[maxN][1 << maxK];
        dp[0][0] = 1;
        for (int curr = 0; curr < 2 * N; ++curr) {
            for (int mask = 0; mask < (1 << K); ++mask) {
                if (dp[curr][mask] == 0) continue; // speed up
                if (mask == 0) {
                    dp[curr + 1][1] += (dp[curr][mask] * 2) % MOD;
                    dp[curr + 1][1] %= MOD;
                } else {
                    int pos = 0, next;
                    for (int i = 0; i < K; ++i) {
                        if ((mask & (1 << i)) != 0) pos = i;
                    }
                    if (pos < K - 1) {
                        next = mask;
                        next <<= 1;
                        ++next;
                        dp[curr + 1][next] += dp[curr][mask];
                        dp[curr + 1][next] %= MOD;
                    }
                    next = mask;
                    next -= (1 << pos);
                    next <<= 1;
                    dp[curr + 1][next] += dp[curr][mask];
                    dp[curr + 1][next] %= MOD;
                }
            }
        }
        return dp[2 * N][0];
    }

    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
    private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, boolean hasAnswer, int p2) {
        System.out.print("Test " + testNum + ": [" + p0 + "," + p1);
        System.out.println("]");
        AlienAndSetDiv2 obj;
        int answer;
        obj = new AlienAndSetDiv2();
        long startTime = System.currentTimeMillis();
        answer = obj.getNumber(p0, p1);
        long endTime = System.currentTimeMillis();
        boolean res;
        res = true;
        System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
        if (hasAnswer) {
            System.out.println("Desired answer:");
            System.out.println("\t" + p2);
        }
        System.out.println("Your answer:");
        System.out.println("\t" + answer);
        if (hasAnswer) {
            res = answer == p2;
        }
        if (!res) {
            System.out.println("DOESN'T MATCH!!!!");
        } else if ((endTime - startTime) / 1000.0 >= 2) {
            System.out.println("FAIL the timeout");
            res = false;
        } else if (hasAnswer) {
            System.out.println("Match :-)");
        } else {
            System.out.println("OK, but is it right?");
        }
        System.out.println("");
        return res;
    }
    public static void main(String[] args) {
        boolean all_right;
        all_right = true;

        int p0;
        int p1;
        int p2;

        // ----- test 0 -----
        p0 = 2;
        p1 = 1;
        p2 = 4;
        all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
        // ------------------

        // ----- test 1 -----
        p0 = 3;
        p1 = 1;
        p2 = 8;
        all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
        // ------------------

        // ----- test 2 -----
        p0 = 4;
        p1 = 2;
        p2 = 44;
        all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
        // ------------------

        // ----- test 3 -----
        p0 = 10;
        p1 = 10;
        p2 = 184756;
        all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
        // ------------------

        if (all_right) {
            System.out.println("You're a stud (at least on the example cases)!");
        } else {
            System.out.println("Some of the test cases had errors.");
        }
    }
    // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
