import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class ElephantDrinkingEasy {
    int n;
    int num = 0;
    int ret = 0;
    char[][] curr;
    ArrayList<Integer> waterI, waterJ;
    public int maxElephants(String[] map) {
        n = map.length;
        curr = new char[n][n];
        for (int i = 0; i < n; i++) {
            curr[i] = map[i].toCharArray();
        }
        waterI = new ArrayList<Integer>();
        waterJ = new ArrayList<Integer>();
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                if (curr[i][j] == 'Y') {
                    waterI.add(i);
                    waterJ.add(j);
                }
            }
        }
        test(0, 0);
        return ret;
    }

    private void test(int step, int direction) {
        ret = Math.max(ret, num);
        if (step == waterI.size()) return;
        int i = waterI.get(step), j = waterJ.get(step);
        if (curr[i][j] == 'Y') {
            ArrayList<Character> track = new ArrayList<Character>();
            boolean ok = true;
            switch (direction) {
            // up
            case 0:
                for (int ii = i; ii >= 0; ii--) {
                    if (curr[ii][j] != 'X') track.add(curr[ii][j]);
                    else ok = false;
                }
                if (ok) {
                    for (int ii = i; ii >= 0; ii--) {
                        curr[ii][j] = 'X';
                    }
                    num++;
                    test(step + 1, 0);
                    for (int ii = i; ii >= 0; ii--) {
                        curr[ii][j] = track.get(i - ii);
                    }
                    num--;
                }
                break;
            // left
            case 1:
                for (int jj = j; jj >= 0; jj--) {
                    if (curr[i][jj] != 'X') track.add(curr[i][jj]);
                    else ok = false;
                }
                if (ok) {
                    for (int jj = j; jj >= 0; jj--) {
                        curr[i][jj] = 'X';
                    }
                    num++;
                    test(step + 1, 0);
                    for (int jj = j; jj >= 0; jj--) {
                        curr[i][jj] = track.get(j - jj);
                    }
                    num--;
                }
                break;
            // down
            case 2:
                for (int ii = i; ii < n; ii++) {
                    if (curr[ii][j] != 'X') track.add(curr[ii][j]);
                    else ok = false;
                }
                if (ok) {
                    for (int ii = i; ii < n; ii++) {
                        curr[ii][j] = 'X';
                    }
                    num++;
                    test(step + 1, 0);
                    for (int ii = i; ii < n; ii++) {
                        curr[ii][j] = track.get(ii - i);
                    }
                    num--;
                }
                break;
            // right
            case 3:
                for (int jj = j; jj < n; jj++) {
                    if (curr[i][jj] != 'X') track.add(curr[i][jj]);
                    else ok = false;
                }
                if (ok) {
                    for (int jj = j; jj < n; jj++) {
                        curr[i][jj] = 'X';
                    }
                    num++;
                    test(step + 1, 0);
                    for (int jj = j; jj < n; jj++) {
                        curr[i][jj] = track.get(jj - j);
                    }
                    num--;
                }
                break;
            }
            if (!ok && direction + 1 < 4) test(step, direction + 1);
            test(step + 1, 0);
        }
    }

    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
    private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, int p1) {
        System.out.print("Test " + testNum + ": [" + "{");
        for (int i = 0; p0.length > i; ++i) {
            if (i > 0) {
                System.out.print(",");
            }
            System.out.print("\"" + p0[i] + "\"");
        }
        System.out.print("}");
        System.out.println("]");
        ElephantDrinkingEasy obj;
        int answer;
        obj = new ElephantDrinkingEasy();
        long startTime = System.currentTimeMillis();
        answer = obj.maxElephants(p0);
        long endTime = System.currentTimeMillis();
        boolean res;
        res = true;
        System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
        if (hasAnswer) {
            System.out.println("Desired answer:");
            System.out.println("\t" + p1);
        }
        System.out.println("Your answer:");
        System.out.println("\t" + answer);
        if (hasAnswer) {
            res = answer == p1;
        }
        if (!res) {
            System.out.println("DOESN'T MATCH!!!!");
        } else if ((endTime - startTime) / 1000.0 >= 2) {
            System.out.println("FAIL the timeout");
            res = false;
        } else if (hasAnswer) {
            System.out.println("Match :-)");
        } else {
            System.out.println("OK, but is it right?");
        }
        System.out.println("");
        return res;
    }
    public static void main(String[] args) {
        boolean all_right;
        all_right = true;

        String[] p0;
        int p1;

        // ----- test 0 -----
        p0 = new String[] {"NNNNN", "NNYYN", "NYNNN", "NNYNN", "NNNNN"};
        p1 = 4;
        all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
        // ------------------

        // ----- test 1 -----
        p0 = new String[] {"YYY", "YYY", "YYY"};
        p1 = 8;
        all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
        // ------------------

        // ----- test 2 -----
        p0 = new String[] {"YNYN", "NNYY", "YYNN", "YYYY"};
        p1 = 10;
        all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
        // ------------------

        // ----- test 3 -----
        p0 = new String[] {"YNYN", "YNYY", "YYNN", "YYYY"};
        p1 = 10;
        all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
        // ------------------

        // ----- test 4 -----
        p0 = new String[] {"YYNYN", "NYNNY", "YNYNN", "YYNYY", "YYNNN"};
        p1 = 12;
        all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
        // ------------------

        // ----- test 5 -----
        p0 = new String[] {"YYNYN", "NYNYY", "YNYYN", "YYNYY", "YYNNN"};
        p1 = 13;
        all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
        // ------------------

        // ----- test 6 -----
        p0 = new String[] {"NN", "NN"};
        p1 = 0;
        all_right = KawigiEdit_RunTest(6, p0, true, p1) && all_right;
        // ------------------

        if (all_right) {
            System.out.println("You're a stud (at least on the example cases)!");
        } else {
            System.out.println("Some of the test cases had errors.");
        }
    }
    // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
