import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class RotatingBot {
    public static int INF = (int) 1e9;

    public int minArea(int[] moves) {
        boolean[][] board = new boolean[200][200];
        int r = 100, c = 100;
        int minR, minC, maxR, maxC;
        minR = minC = 100;
        maxR = maxC = 100;
        board[r][c] = true;
        int[][] direct = new int[][]{{0, 1}, {-1, 0}, {0, -1}, {1, 0}};
        int currD = 0;
        for (int k = 0; k < moves.length; k++) {
            int m = moves[k];
            for (int i = 0; i < m; i++) {
                r += direct[currD][0];
                c += direct[currD][1];
                if (board[r][c]) return -1;
                board[r][c] = true;
                minR = Math.min(minR, r);
                minC = Math.min(minC, c);
                maxR = Math.max(maxR, r);
                maxC = Math.max(maxC, c);
            }

            int nextR = r + direct[currD][0];
            int nextC = c + direct[currD][1];
            if (nextR <= maxR
                    && nextR >= minR
                    && nextC <= maxC
                    && nextC >= minC
                    && !board[nextR][nextC]
                    && (k + 1) < moves.length
                    ) {
                return -1;
            }
            currD++;
            currD %= 4;
        }
        return (maxR - minR + 1) * (maxC - minC + 1);
    }

    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
    private static boolean KawigiEdit_RunTest(int testNum, int[] p0, boolean hasAnswer, int p1) {
        System.out.print("Test " + testNum + ": [" + "{");
        for (int i = 0; p0.length > i; ++i) {
            if (i > 0) {
                System.out.print(",");
            }
            System.out.print(p0[i]);
        }
        System.out.print("}");
        System.out.println("]");
        RotatingBot obj;
        int answer;
        obj = new RotatingBot();
        long startTime = System.currentTimeMillis();
        answer = obj.minArea(p0);
        long endTime = System.currentTimeMillis();
        boolean res;
        res = true;
        System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
        if (hasAnswer) {
            System.out.println("Desired answer:");
            System.out.println("\t" + p1);
        }
        System.out.println("Your answer:");
        System.out.println("\t" + answer);
        if (hasAnswer) {
            res = answer == p1;
        }
        if (!res) {
            System.out.println("DOESN'T MATCH!!!!");
        } else if ((endTime - startTime) / 1000.0 >= 2) {
            System.out.println("FAIL the timeout");
            res = false;
        } else if (hasAnswer) {
            System.out.println("Match :-)");
        } else {
            System.out.println("OK, but is it right?");
        }
        System.out.println("");
        return res;
    }

    public static void main(String[] args) {
        boolean all_right;
        all_right = true;

        int[] p0;
        int p1;
        // ----- test 7 -----
        p0 = new int[]{1, 2, 3, 4, 5};
        p1 = -1;
        all_right = KawigiEdit_RunTest(7, p0, true, p1) && all_right;
        // ------------------

        // ----- test 7 -----
        p0 = new int[]{5, 4, 5, 3, 3};
        p1 = 30;
        all_right = KawigiEdit_RunTest(7, p0, true, p1) && all_right;
        // ------------------

        // ----- test 0 -----
        p0 = new int[]{15};
        p1 = 16;
        all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
        // ------------------

        // ----- test 1 -----
        p0 = new int[]{3, 10};
        p1 = 44;
        all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
        // ------------------

        // ----- test 2 -----
        p0 = new int[]{1, 1, 1, 1};
        p1 = -1;
        all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
        // ------------------

        // ----- test 3 -----
        p0 = new int[]{9, 5, 11, 10, 11, 4, 10};
        p1 = 132;
        all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
        // ------------------

        // ----- test 4 -----
        p0 = new int[]{12, 1, 27, 14, 27, 12, 26, 11, 25, 10, 24, 9, 23, 8, 22, 7, 21, 6, 20, 5, 19, 4, 18, 3, 17, 2, 16, 1, 15};
        p1 = 420;
        all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
        // ------------------

        // ----- test 5 -----
        p0 = new int[]{8, 6, 6, 1};
        p1 = -1;
        all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
        // ------------------

        // ----- test 6 -----
        p0 = new int[]{8, 6, 6};
        p1 = 63;
        all_right = KawigiEdit_RunTest(6, p0, true, p1) && all_right;
        // ------------------

        if (all_right) {
            System.out.println("You're a stud (at least on the example cases)!");
        } else {
            System.out.println("Some of the test cases had errors.");
        }
    }
    // PROBLEM STATEMENT
    // NOTE: This problem statement contains images that may not display properly if viewed outside of the applet.
    //
    // We had a rectangular grid that consisted of W x H square cells.
    // We placed a robot on one of the cells.
    // The robot then followed the rules given below.
    //
    //
    // Initially, the robot is facing east.
    // The robot moves in steps. In each step it moves to the adjacent cell in the direction it currently faces.
    // The robot may not leave the grid.
    // The robot may not visit the same cell twice. (This also means that it may not reenter the starting cell.)
    // If a step forward does not cause the robot to break the above rules, the robot takes the step.
    // Otherwise, the robot rotates 90 degrees to the left (counter-clockwise) and checks whether a step forward still breaks the above rules.
    //   If not, the robot takes the step and continues executing this program (still rotated in the new direction).
    // If the rotation left did not help, the robot terminates the execution of this program.
    // We can also terminate the execution of the program manually, at any moment.
    //
    // For example, the following seven images show a series of moves made by the robot in a 12 x 11 board:
    //
    //
    // We forgot the dimensions of the grid and the original (x,y) coordinates of the cell on which the robot was originally placed, but we do remember its movement. You are given a int[] moves. This sequence of positive integers shall be interpreted as follows:
    // The robot performed moves[0] steps eastwards, turned left, performed moves[1] steps northwards, turned left, and so on.
    // After performing the last sequence of steps, the robot stopped. (Either it detected that it should terminate, or we stopped it manually.) We are not sure if the sequence of moves is valid. If the sequence of moves is impossible, return -1. Else, return the minimum area of a grid in which the sequence of moves is possible.
    // (I.e., the return value is the smallest possible value of the product of W and H.).
    //
    // DEFINITION
    // Class:RotatingBot
    // Method:minArea
    // Parameters:int[]
    // Returns:int
    // Method signature:int minArea(int[] moves)
    //
    //
    // CONSTRAINTS
    // -moves will contain between 1 and 50 elements, inclusive.
    // -Each element of moves will be between 1 and 50, inclusive.
    //
    //
    // EXAMPLES
    //
    // 0)
    // {15}
    //
    // Returns: 16
    //
    // The smallest valid board is a 16x1 board, with the robot starting on the west end of the board.
    //
    // 1)
    // {3,10}
    //
    // Returns: 44
    //
    // The smallest solution is to place the robot into the southwest corner of a 4 x 11 board.
    //
    // 2)
    // {1,1,1,1}
    //
    // Returns: -1
    //
    // This sequence of moves is not possible because the robot would return to its initial location which is forbidden.
    //
    // 3)
    // {9,5,11,10,11,4,10}
    //
    // Returns: 132
    //
    // These moves match the image from the problem statement.
    //
    // 4)
    // {12,1,27,14,27,12,26,11,25,10,24,9,23,8,22,7,21,6,20,5,19,4,18,3,17,2,16,1,15}
    //
    // Returns: 420
    //
    // 5)
    // {8,6,6,1}
    //
    // Returns: -1
    //
    //
    //
    // 6)
    // {8,6,6}
    //
    // Returns: 63
    //
    //
    //
    // 7)
    // {5,4,5,3,3}
    //
    // Returns: 30
    //
    //
    //
    // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
