import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class TheJediTestDiv2
{
	public int countSupervisors(int[] students, int Y, int J)
	{
	    int n = students.length;
        int[] hasY = new int[n];
        int[] onlyJ = new int[n];
        for (int i = 0; i < n; i++) {
            int curr = students[i];
            curr -= Y;
            if (curr % J == 0) {
                hasY[i] = curr / J;
            } else {
                hasY[i] = curr / J + 1;
            }

            curr = students[i];
            if (curr % J == 0) {
                onlyJ[i] = curr / J;
            } else {
                onlyJ[i] = curr / J + 1;
            }
        }
        int sum = 0;
        for (int i = 0; i < n; i++) {
            sum += onlyJ[i];
        }
        int ret = sum;
        for (int i = 0; i < n; i++) {
            ret = Math.min(ret, sum - onlyJ[i] + hasY[i]);
        }
        return Math.max(0, ret);
    }
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int p1, int p2, boolean hasAnswer, int p3) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}" + "," + p1 + "," + p2);
		System.out.println("]");
		TheJediTestDiv2 obj;
		int answer;
		obj = new TheJediTestDiv2();
		long startTime = System.currentTimeMillis();
		answer = obj.countSupervisors(p0, p1, p2);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p3);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p3;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int[] p0;
		int p1;
		int p2;
		int p3;
		
		// ----- test 0 -----
		p0 = new int[]{10,15};
		p1 = 12;
		p2 = 5;
		p3 = 3;
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new int[]{11,13,15};
		p1 = 9;
		p2 = 5;
		p3 = 7;
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new int[]{10};
		p1 = 100;
		p2 = 2;
		p3 = 0;
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new int[]{0,0,0,0,0};
		p1 = 145;
		p2 = 21;
		p3 = 0;
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new int[]{4,7,10,5,6,55,2};
		p1 = 20;
		p2 = 3;
		p3 = 26;
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// A long time ago in a galaxy far, far away the Jedi Academy conducted a test to detect children with high Force sensitivy which would then be trained to become Jedi. The test was conducted in the Jedi Temple which had several floors. You are given a int[] students which has as many elements as there are floors in the building.
	// For each i, students[i] is the number of children on the i-th floor (0-based index).
	// 
	// During the test, the children will be supervised by Yoda and possibly also by some other Jedi. Each Jedi, including Yoda, can only supervise children on one of the floors.
	// Additionally, there is a limit on how many children a single Jedi may supervise: Yoda is able to supervise up to Y children, inclusive, and any other Jedi is able to supervise up to J children, inclusive. Each child has to be supervised by some Jedi.
	// 
	// For example:
	// Yoda and a single other Jedi can supervise a floor that contains up to Y+J children.
	// Two Jedi can supervise a floor that contains up to 2J children.
	// 
	// Find the minimum number of Jedi which were required to help Yoda so that every child at each floor was supervised. Note that Yoda may choose which floor he wants to supervise, and that the answer may sometimes be zero.
	// 
	// 
	// DEFINITION
	// Class:TheJediTestDiv2
	// Method:countSupervisors
	// Parameters:int[], int, int
	// Returns:int
	// Method signature:int countSupervisors(int[] students, int Y, int J)
	// 
	// 
	// CONSTRAINTS
	// -students will contain between 1 and 50 elements, inclusive.
	// -Each element in students will be between 0 and 1000, inclusive.
	// -J will be between 1 and 999, inclusive.
	// -Y will be between J+1 and 1000, inclusive.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// {10, 15}
	// 12
	// 5
	// 
	// Returns: 3
	// 
	// Yoda can supervise at most 12 children, so he can either supervise all kids on floor 0, or 12 out of the 15 children on floor 1. If Yoda supervises floor 0, we need three other Jedi on floor 1. If Yoda supervises a part of floor 1, we need one other Jedi on floor 1 and two more for floor 0. In either case, there have to be at least 3 Jedi other than Yoda.
	// 
	// 
	// 1)
	// {11, 13, 15}
	// 9
	// 5
	// 
	// Returns: 7
	// 
	// In the optimal solution, Yoda will supervise either on floor 0 or on floor 1.
	// In either case we need one Jedi to help him on his floor, and three Jedi for each of the other two floors.
	// Note that if Yoda chooses floor 2, eight additional Jedi would be needed.
	// 
	// 2)
	// {10}
	// 100
	// 2
	// 
	// Returns: 0
	// 
	// Yoda can handle the entire floor.
	// 
	// 3)
	// {0, 0, 0, 0, 0}
	// 145
	// 21
	// 
	// Returns: 0
	// 
	// For the Jedi Academy, a bad day it was.
	// 
	// 4)
	// {4, 7, 10, 5, 6, 55, 2}
	// 20
	// 3
	// 
	// Returns: 26
	// 
	// 
	// 
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
